# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20170920_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='VmHost',
        ),
    ]
