# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('opsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=30, null=True)),
                ('is_virtual', models.CharField(blank=True, max_length=30, null=True)),
                ('minion_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('minion_status', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('applications', models.ManyToManyField(to='opsdb.Application')),
                ('environment', models.ManyToManyField(to='opsdb.Environment')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'db_table': 'hostgroup',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroups',
            field=models.ManyToManyField(to='opsdb.HostGroup'),
        ),
    ]
