# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0004_auto_20170905_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('argument', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'command',
            },
        ),
    ]
