# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0006_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
