# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0009_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='upload', max_length=20),
        ),
    ]
