# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0010_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
