# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0013_blackcommand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackCommand',
        ),
        migrations.AddField(
            model_name='cmd',
            name='command_type',
            field=models.CharField(default='common', max_length=80),
        ),
        migrations.AddField(
            model_name='cmd',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmd',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
