# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0014_auto_20170918_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='server_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
