# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0015_host_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='server_id',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
