# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0016_auto_20170921_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='server_id',
            field=models.CharField(blank=True, default='server_id', max_length=200, null=True),
        ),
    ]
